### ISSUE TITLE
Sanitize

### ISSUE THREAD

**Issue by ear1grey** [portsoc/chator#10]
The app will be storing and sharing strings created by users.
Those strings may be malicious and
* damage our servers, or
* be used to attack other users
if we do not adequately sanitize them.

**Comment by Lagicrus** [comment]
Or allow users to send HTML/js code which the browser could still run. Seen before when a user was able to send js code for a popup message. Every user connected would have a popup appear on their screens due to lack of sanitation.

**Comment by jacekkopecky** [comment]
Users submitting scripts that run automatically would be a huge security hole – something we prefer to avoid.

We'll talk about sanitising when we build a server.

**Comment by jacekkopecky** [comment]
must also address XSS

**Comment by ear1grey** [comment]
Now handled by server and client.
