### ISSUE TITLE
peer to peer mode var WebRTC

### ISSUE THREAD

**Issue by UP822718** [portsoc/chator#13]
use webRTC to do a p2p connection between clients instead of having to rely instead on a server to communicate new messages to the client

**Comment by Lagicrus** [comment]
An alternate measure could be the usage of a password to encrypt the chat going back and forth.
An extension to this idea would be to have private chat rooms.

**Comment by ear1grey** [comment]
At the moment the core concept is a board that holds only 50 messages.  You post, and then (an arbitrary amount of time later) based on how many other people are posting, the message disappears.

**Comment by jacekkopecky** [comment]
Nice idea, but WebRTC is well out of scope of what we can do in these WebF1 lectures. Definitely something for the year-2 module.
