### ISSUE TITLE
If user triggers status code 400 and the like have a response on the client side

### ISSUE THREAD

**Issue by Lagicrus** [portsoc/chator#20]
E.g. If the client triggers a code 400 error on the message send due to a blank message. Have a popup appear saying "You can't do this because X" or the like, so the client understands what they did wrong.

**Comment by ear1grey** [comment]
I like this.  The user can't really do anything wrong given the simplicity fo the interface, but a nice little message injected into the list along with all the other user-generated messages would be good.  It'll need a different class so it can be recognised as different.

**Comment by ear1grey** [comment]
We'd prefer the UI to only allow 'right things' to be done, so that we don't need to inform users that they've done something wrong.  Keep it (painfully) simple.
