### ISSUE TITLE
issue with emoji

### ISSUE THREAD

**Issue by jacekkopecky** [portsoc/chator#22]
I suspect there might be an issue with emoji now because by default the DB may not support UTF8 but it can be enabled.

**Comment by Lagicrus** [comment]
I agree with this, and also extend the idea that you might encounter issues with the skin tone modified emotes https://emojipedia.org/unicode-8.0/ https://emojipedia.org/emoji-modifier-fitzpatrick-type-1-2/ . Which could display it incorrectly to the client / store it badly which might extend to corruption of that message.
