### ISSUE TITLE
Pre-empt Login Fails

### ISSUE THREAD

**Issue by ear1grey** [portsoc/chator#29]
Anyone with ad-blocking or privacy software (so, everyone) needs to be warned on the login page that they should whitelist the site or login will not work, and you'll not be able to do a nice error handler.
<img width="524" alt="screen shot 2018-03-27 at 04 59 20" src="https://user-images.githubusercontent.com/409687/37946128-bea03d5e-317b-11e8-9e3e-0c31d5cd5e49.png">

**Comment by jacekkopecky** [comment]
wrong repo
