### ISSUE TITLE
Bug where you can go over 50 messages at once in chat

### ISSUE THREAD

**Issue by Lagicrus** [portsoc/chator#9]
Custom limit it on a user by user bases

**Comment by ear1grey** [comment]
- The 50 message limit should be maintained/imposed by both client and server. 
- When messages are first requested, up to 50 will be loaded.
- When subsequent messages are requested we must either remove all previous messages and replace with the latest 50 messages, or, insert only the new messages into the top of the list, and cull those that are outside the 50 limit.
- If we wish to include images and videos as in #6 then the more intelligent integration of the new list with the old is preferable to reduce bandwidth.

**Comment by jacekkopecky** [comment]
fixed in 05dc9c8705c451d1f7f1fe3b87b4c49496c519a4 – the server keeps only 50 messages, the client doesn't remember any
